# Anything apart from this follows from the default configuration
[mgr]
ratio = [1, 3, 4]
sort_by = "alphabetical"
sort_dir_first = true
linemode = "none"
show_hidden = true
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll", "touch", "move", "drag"]

[preview]
wrap = "yes"
tab_size = 2
max_width = 1200
max_height = 1800

[opener]
edit = [
    { run = 'hx "$@"', desc = "helix", block = true, for = "unix" },
    { run = 'code "$@"', desc = "VS Code", block = false, for = "unix" },
    { run = 'code %*', orphan = true, desc = "code", for = "windows" },
    { run = 'code -w %*', block = true, desc = "code (block)", for = "windows" },
]
open = [
    { run = 'xdg-open "$1"', desc = "Open", for = "linux" },
    { run = 'code "$@"', desc = "VS Code", for = "linux" },
    { run = 'open "$@"', desc = "Open", for = "macos" },
    { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]
[plugin]

prepend_previewers = [
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
    { name = "*.md", run  = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'},
    { name = "*.{pdb,pqr}", run = "code" },
    { mime = "audio/*", run = "exifaudio" },
    { mime = "application/x-bittorrent", run = "torrent-preview" },
    { name = "*.ipynb", run = 'piper -- rich -j --left --panel=rounded --guides --line-numbers --force-terminal "$1"'},
    { name = "*.json", run = 'piper -- rich -j --left --panel=rounded --guides --line-numbers --force-terminal "$1"'},
    { name = "*.rst", run = 'piper -- rich -j --left --panel=rounded --guides --line-numbers --force-terminal "$1"'},
    { name = "*.csv", run = 'piper -- rich -j --left --panel=rounded --guides --line-numbers --force-terminal "$1"'},
]

#[[plugin.prepend_fetchers]]
#id   = "mactag"
#name = "*"
#run  = "mactag"
#
#[[plugin.prepend_fetchers]]
#id   = "mactag"
#name = "*/"
#run  = "mactag"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
